---
'$schema': http://json.schemastore.org/prettierrc
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
importOrder:
  - '^@/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderCaseInsensitive: true
importOrderParserPlugins:
  - typescript
  - jsx
singleQuote: true
trailingComma: all
bracketSpacing: true
useTabs: false
printWidth: 100
proseWrap: preserve
